import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Fustat, Roboto } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});
const fustat = Fustat({
  subsets: ["latin"],
  variable: "--font-fustat",
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

// const nohemi = localFont({
//   src: [
//     {
//       path: "../../public/fonts/Nohemi-Regular.woff2",
//       weight: "400",
//     },
//     {
//       path: "../../public/fonts/Nohemi-Bold.woff2",
//       weight: "700",
//     },
//   ],
//   variable: "--font-nohemi",
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} ${outfit.variable} ${fustat.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
